name: CI
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        java: [8, 11]
        scala: [2.11.12, 2.12.13, 2.13.5]
        postgres: [11]
    name: Test (Postgres ${{ matrix.postgres }} Scala ${{ matrix.scala }} Java ${{ matrix.java }})
    runs-on: ubuntu-latest
    env:
      SLICK_PG_TEST_POSTGRES_IMAGE_TAG: ${{ matrix.postgres }}
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - uses: actions/setup-node@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ++${{ matrix.scala }} test